from typing import Any, Protocol

from numpy.typing import NDArray

type TVector = NDArray[Any]
type TMatrix = NDArray[Any]


DEFAULT_PORT = 5050
DEFAULT_AUTHKEY = b"sage"

# https://doc.sagemath.org/html/en/reference/modules/sage/modules/free_module_integer.html
# https://doc.sagemath.org/html/en/reference/cryptography/sage/crypto/lattice.html
# https://doc.sagemath.org/html/en/reference/matrices/sage/matrix/matrix_integer_dense.html#sage.matrix.matrix_integer_dense.Matrix_integer_dense.echelon_form
# https://doc.sagemath.org/html/en/reference/matrices/sage/matrix/matrix2.html#sage.matrix.matrix2.Matrix.gram_schmidt


class SageEngineInterface(Protocol):
    def gen_lattice(self, type: str, n: int, m: int, q: int, seed: int | None, quotient: TVector | None, dual: bool) -> TMatrix: ...

    def lll(self, lattice_basis: TMatrix, delta: float, transformation: bool) -> TMatrix | tuple[TMatrix, TMatrix]: ...

    def bkz(self, lattice_basis: TMatrix, delta: float, block_size: int) -> TMatrix: ...

    def hkz(self, lattice_basis: TMatrix) -> TMatrix: ...

    def shortest_vector(self, lattice_basis: TMatrix) -> TVector: ...

    def closest_vector(self, lattice_basis: TMatrix, target_vector: TVector) -> TVector: ...

    def babai(self, algorithm: str, lattice_basis: TMatrix, target_vector: TVector, delta: float) -> TVector: ...

    def discriminant(self, lattice_basis: TMatrix) -> int: ...

    def gaussian_heuristic(self, lattice_basis: TMatrix) -> float: ...

    def hadamard_ratio(self, lattice_basis: TMatrix) -> float: ...

    def is_unimodular(self, lattice_basis: TMatrix) -> bool: ...

    def volume(self, lattice_basis: TMatrix) -> int: ...

    def hnf(self, matrix: TMatrix, transformation: bool) -> TMatrix | tuple[TMatrix, TMatrix]: ...

    def is_lll_reduced(self, lattice_basis: TMatrix, delta: float) -> bool: ...

    def gso(self, matrix: TMatrix, orthonormal: bool) -> tuple[TMatrix, TMatrix]: ...

    def left_kernel(self, matrix: TMatrix) -> TMatrix: ...

    def left_nullity(self, matrix: TMatrix) -> int: ...

    def right_kernel(self, matrix: TMatrix) -> TMatrix: ...

    def right_nullity(self, matrix: TMatrix) -> int: ...

    def rank(self, matrix: TMatrix) -> int: ...
