on: push

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.12'
            - name: Install uv
              run: |
                curl -LsSf https://astral.sh/uv/install.sh | sh
                echo "${HOME}/.cargo/bin" >> $GITHUB_PATH

            - name: Install tests dependencies with uv
              run: |
                uv sync --group tests

            - name: Run tests with pytest
              run: |
                pytest
